language: "zh"

pipeline:
  - name: "components.kashgari_intent_classifier.KashgariIntentClassifier"
    bert_model_path: "/opt/mt/rasa/rasa_bert/google/chinese_wwm_ext_L-12_H-768_A-12"
    use_cudnn_cell: False
    sequence_length: 32

  - name: "components.kashgari_entity_extractor.KashgariEntityExtractor"
    bert_model_path: "/opt/mt/rasa/rasa_bert/google/chinese_wwm_ext_L-12_H-768_A-12"
    use_cudnn_cell: False
    sequence_length: 32

policies:
  - name: "policy.policy.CustomPolicy"
    epochs: 100
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 3
      state_featurizer:
        - name: LabelTokenizerSingleStateFeaturizer
    tf_config: {
      "inter_op_parallelism_threads": 0,
      "intra_op_parallelism_threads": 0,
      "gpu_options": {"allow_growth": True}
    }

  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
    nlu_threshold: 0.5
    core_threshold: 0.3
  - name: MemoizationPolicy
    max_history: 3
